#!/bin/sh

# TCL Template Filename. Leave this here
# to let the config decide if the base template is
# correct for the project
TCL_TEMP_FILE=../../zynq_bp.tcl.in

# The fpga device we are building for
FPGA_DEVICE=xc7z020clg400-3
FPGA_DEV_SHORT=7z020

# Base Project Name
PRJ_NAME=prototype_"$FPGA_DEV_SHORT"

# The board part file url, if the target has one
BOARD_PART="krtkl.com:snickerdoodle_black:part0:1.0"

# The physical package pin constraint file
PIN_HW_XDC_FILE=const/prototype_pinmap.xdc

# The filename of the top level block diagram
TOP_LEVEL_BD_FILE=scripts/prototype_bd.tcl

## HostMot2 Pin constraints - these update the IP. Physical pin constraints
#  belong in an xdc file above

# HM2 Pin Filename relative to project folder
PIN_FILE=const/PIN_PROTOTYPE.vhd
# Pin package name defined in above pin file
PIN_NAME=PIN_PROTOTYPE
#FWID File name in the const folder
FWID_NAME=FWID_PROTOTYPE

############################################################################
# HostMot2 Generic Parameters, autofills IP correctly without regenerating
# block diagram script
############################################################################

# The name of the board to compile into the IP. Matches board name in hal files
BOARD_NAME_HIGH_HEX=544F5250     #PROT
BOARD_NAME_LOW_HEX=45494B43      #TEST
